on:
  workflow_dispatch:
  workflow_call:

name: Deploy QA on Demand

jobs:
  echo-test:
    name: Echo Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo "Bobby Jones!"
          cat README.md
