on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branchName:
        required: false
        type: string
        default: master

name: Deploy QA on Demand

jobs:
  echo-test:
    name: Echo Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - run: |
          echo "Bobby Jones!"
          cat README.md
