on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

name: Echo Test
jobs:
  echo-test:
    name: Echo Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/bobtest
        with:
          secrets: secrets
