on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

name: Failing Test

jobs:
  fail-test:
    name: Fail Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          ./fail.sh
