name: Test PR Comments
on:
  issue_comment:
    types: [created, edited]

jobs:
  fetch_branch:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.fetch.name }}
    steps:
      - name: Fetch Branch
        id: fetch
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            }).then( (pr) => {
              console.log(`::set-output name=name::${pr.data.head.ref}`);
            })

  comment:
    needs: branch
    secrets: inherit
    if: (github.event.issue.pull_request != null) &&  contains(github.event.comment.body, '/blahblah')
    uses: ./.github/workflows/echo_test.yml
    with:
      branchName: ${{ needs.fetch_branch.outputs.name }}

  pr-info:
    needs: comment
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Blah blah blah blog\nhttps://google.com/?s=${{ needs.branch.outputs.name }}"
            })
