name: Test PR Comments
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-test:
    secrets: inherit
    if: (github.event.issue.pull_request != null) &&  contains(github.event.comment.body, '/blahblah')
    uses: ./.github/workflows/echo_test.yml

  pr-info:
    needs: comment-test
    runs-on: ubuntu-latest
    steps:
      - name: PR Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // Get the branch name
            github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            }).then( (pr) => {
            
              // use the branch name to make a comment  on the PR with a Binder badge
              var BRANCH_NAME = pr.data.head.ref
              github.issues.createComment({
                issue_number: context.payload.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Blah blah blah blog\nhttps://google.com/?s=${BRANCH_NAME}`
              })
            })