on:
  release:
    types:
      - published

name: test release

jobs:
  build:
    name: echo stuff
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "New release "${{ github.head_ref }}

