on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

name: Testing Job Container
jobs:
  job-container:
    runs-on: ubuntu-latest
    container: pguilbault/symfony-gh-actions:v0.1.2
    steps:
      - name: Test Symfony Command
        run: /app/bin/console pr:info 2
