on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

name: Testing Job Container
jobs:
  job-container:
    runs-on: ubuntu-latest
    container: pguilbault/symfony-gh-actions:v0.1.4
    env:
      GITHUB_USERNAME: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ORG: Bwen
      GITHUB_REPO: test
    steps:
      - name: Test Symfony Command
        run: docker ps -a
